In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import requests
from tensorflow.keras.layers import *
from tensorflow.keras.models import *
from datetime import datetime
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv('./data/eighthr.data', header =None,index_col=0)
df

,1,2,3,4,5,6,7,8,9,10,...,64,65,66,67,68,69,70,71,72,73
0,,,,,,,,,,,,,,,,,,,,,
1/1/1998,0.8,1.8,2.4,2.1,2,2.1,1.5,1.7,1.9,2.3,...,0.15,10.67,-1.56,5795,-12.1,17.9,10330,-55,0,0.0
1/2/1998,2.8,3.2,3.3,2.7,3.3,3.2,2.9,2.8,3.1,3.4,...,0.48,8.39,3.84,5805,14.05,29,10275,-55,0,0.0
1/3/1998,2.9,2.8,2.6,2.1,2.2,2.5,2.5,2.7,2.2,2.5,...,0.6,6.94,9.8,5790,17.9,41.3,10235,-40,0,0.0
1/4/1998,4.7,3.8,3.7,3.8,2.9,3.1,2.8,2.5,2.4,3.1,...,0.49,8.73,10.54,5775,31.15,51.7,10195,-40,2.08,0.0
1/5/1998,2.6,2.1,1.6,1.4,0.9,1.5,1.2,1.4,1.3,1.4,...,?,?,?,?,?,?,?,?,0.58,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12/27/2004,0.3,0.4,0.5,0.5,0.2,0.3,0.4,0.4,1.3,2.2,...,0.07,7.93,-4.41,5800,-25.6,21.8,10295,65,0,0.0
12/28/2004,1,1.4,1.1,1.7,1.5,1.7,1.8,1.5,2.1,2.4,...,0.04,5.95,-1.14,5845,-19.4,19.1,10310,15,0,0.0
12/29/2004,0.8,0.8,1.2,0.9,0.4,0.6,0.8,1.1,1.5,1.5,...,0.06,7.8,-0.64,5845,-9.6,35.2,10275,-35,0,0.0
12/30/2004,1.3,0.9,1.5,1.2,1.6,1.8,1.1,1,1.9,2,...,0.25,7.72,-0.89,5845,-19.6,34.2,10245,-30,0.05,0.0
12/31/2004,1.5,1.3,1.8,1.4,1.2,1.7,1.6,1.4,1.6,3,...,0.54,13.07,9.15,5820,1.95,39.35,10220,-25,0,0.0

In [3]:
df = df.iloc[:,1:].apply(pd.to_numeric,errors='coerce') # 오 좋은데?
df

,2,3,4,5,6,7,8,9,10,11,...,64,65,66,67,68,69,70,71,72,73
0,,,,,,,,,,,,,,,,,,,,,
1/1/1998,1.8,2.4,2.1,2.0,2.1,1.5,1.7,1.9,2.3,3.7,...,0.15,10.67,-1.56,5795.0,-12.10,17.90,10330.0,-55.0,0.00,0.0
1/2/1998,3.2,3.3,2.7,3.3,3.2,2.9,2.8,3.1,3.4,4.2,...,0.48,8.39,3.84,5805.0,14.05,29.00,10275.0,-55.0,0.00,0.0
1/3/1998,2.8,2.6,2.1,2.2,2.5,2.5,2.7,2.2,2.5,3.1,...,0.60,6.94,9.80,5790.0,17.90,41.30,10235.0,-40.0,0.00,0.0
1/4/1998,3.8,3.7,3.8,2.9,3.1,2.8,2.5,2.4,3.1,3.3,...,0.49,8.73,10.54,5775.0,31.15,51.70,10195.0,-40.0,2.08,0.0
1/5/1998,2.1,1.6,1.4,0.9,1.5,1.2,1.4,1.3,1.4,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.58,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12/27/2004,0.4,0.5,0.5,0.2,0.3,0.4,0.4,1.3,2.2,2.8,...,0.07,7.93,-4.41,5800.0,-25.60,21.80,10295.0,65.0,0.00,0.0
12/28/2004,1.4,1.1,1.7,1.5,1.7,1.8,1.5,2.1,2.4,4.2,...,0.04,5.95,-1.14,5845.0,-19.40,19.10,10310.0,15.0,0.00,0.0
12/29/2004,0.8,1.2,0.9,0.4,0.6,0.8,1.1,1.5,1.5,2.9,...,0.06,7.80,-0.64,5845.0,-9.60,35.20,10275.0,-35.0,0.00,0.0
12/30/2004,0.9,1.5,1.2,1.6,1.8,1.1,1.0,1.9,2.0,2.5,...,0.25,7.72,-0.89,5845.0,-19.60,34.20,10245.0,-30.0,0.05,0.0
12/31/2004,1.3,1.8,1.4,1.2,1.7,1.6,1.4,1.6,3.0,3.6,...,0.54,13.07,9.15,5820.0,1.95,39.35,10220.0,-25.0,0.00,0.0

In [4]:
 df.isnull().sum()

2     292
3     294
4     292
5     293
6     292
     ...
69    125
70     95
71    158
72      2
73      0
Length: 72, dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df

,2,3,4,5,6,7,8,9,10,11,...,64,65,66,67,68,69,70,71,72,73
0,,,,,,,,,,,,,,,,,,,,,
1/1/1998,1.8,2.4,2.1,2.0,2.1,1.5,1.7,1.9,2.3,3.7,...,0.15,10.67,-1.56,5795.0,-12.10,17.90,10330.0,-55.0,0.00,0.0
1/2/1998,3.2,3.3,2.7,3.3,3.2,2.9,2.8,3.1,3.4,4.2,...,0.48,8.39,3.84,5805.0,14.05,29.00,10275.0,-55.0,0.00,0.0
1/3/1998,2.8,2.6,2.1,2.2,2.5,2.5,2.7,2.2,2.5,3.1,...,0.60,6.94,9.80,5790.0,17.90,41.30,10235.0,-40.0,0.00,0.0
1/4/1998,3.8,3.7,3.8,2.9,3.1,2.8,2.5,2.4,3.1,3.3,...,0.49,8.73,10.54,5775.0,31.15,51.70,10195.0,-40.0,2.08,0.0
1/7/1998,3.2,3.8,5.1,6.0,7.0,6.3,6.4,6.3,5.4,6.1,...,0.84,6.86,25.60,5695.0,26.75,48.45,10040.0,-80.0,0.18,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12/27/2004,0.4,0.5,0.5,0.2,0.3,0.4,0.4,1.3,2.2,2.8,...,0.07,7.93,-4.41,5800.0,-25.60,21.80,10295.0,65.0,0.00,0.0
12/28/2004,1.4,1.1,1.7,1.5,1.7,1.8,1.5,2.1,2.4,4.2,...,0.04,5.95,-1.14,5845.0,-19.40,19.10,10310.0,15.0,0.00,0.0
12/29/2004,0.8,1.2,0.9,0.4,0.6,0.8,1.1,1.5,1.5,2.9,...,0.06,7.80,-0.64,5845.0,-9.60,35.20,10275.0,-35.0,0.00,0.0
12/30/2004,0.9,1.5,1.2,1.6,1.8,1.1,1.0,1.9,2.0,2.5,...,0.25,7.72,-0.89,5845.0,-19.60,34.20,10245.0,-30.0,0.05,0.0
12/31/2004,1.3,1.8,1.4,1.2,1.7,1.6,1.4,1.6,3.0,3.6,...,0.54,13.07,9.15,5820.0,1.95,39.35,10220.0,-25.0,0.00,0.0

In [10]:
x = df.iloc[:,:-1].values
x.shape

(1847, 71)

In [12]:
# CNN을 위해 3차원
x.reshape(1847,71,1)

array([[[ 1.8000e+00],
        [ 2.4000e+00],
        [ 2.1000e+00],
        ...,
        [ 1.0330e+04],
        [-5.5000e+01],
        [ 0.0000e+00]],

       [[ 3.2000e+00],
        [ 3.3000e+00],
        [ 2.7000e+00],
        ...,
        [ 1.0275e+04],
        [-5.5000e+01],
        [ 0.0000e+00]],

       [[ 2.8000e+00],
        [ 2.6000e+00],
        [ 2.1000e+00],
        ...,
        [ 1.0235e+04],
        [-4.0000e+01],
        [ 0.0000e+00]],

       ...,

       [[ 8.0000e-01],
        [ 1.2000e+00],
        [ 9.0000e-01],
        ...,
        [ 1.0275e+04],
        [-3.5000e+01],
        [ 0.0000e+00]],

       [[ 9.0000e-01],
        [ 1.5000e+00],
        [ 1.2000e+00],
        ...,
        [ 1.0245e+04],
        [-3.0000e+01],
        [ 5.0000e-02]],

       [[ 1.3000e+00],
        [ 1.8000e+00],
        [ 1.4000e+00],
        ...,
        [ 1.0220e+04],
        [-2.5000e+01],
        [ 0.0000e+00]]])

In [11]:
y= df.iloc[:,-1].values
y.shape

(1847,)

In [ ]:
# train,test
from