In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_gu = pd.read_csv('./data/구제역타겟추가.csv',index_col=0)
# df_gu

,시간,서울평균 기온,서울최저 기온,서울최고 기온,서울1시간 최다강수량,서울일강수량,서울최대 순간풍속,서울최대 순간 풍속 풍향,서울최대 풍속,서울최대 풍속 풍향,...,지난최고기온,지난최저기온,지난습도,지난풍향,지난풍속,지난강수량,지난해면기압,지난이슬점 온도,자외선 B 일최고값,산불발생여부
0,2003-01-01,-4.7,-7.1,-1.0,0.0,0.0,9.9,270.0,5.9,270.0,...,0.1,-8.9,43.6875,280.0,3.250,0.00000,1034.7250,-14.2875,NaN,0.0
1,2003-01-02,-4.3,-9.2,0.0,0.0,0.0,7.5,70.0,4.3,270.0,...,0.1,-8.5,62.7750,80.0,4.125,0.00000,1032.0750,-9.7375,NaN,0.0
2,2003-01-03,-3.6,-6.8,-0.3,0.0,1.3,15.2,340.0,7.1,320.0,...,-5.5,-13.0,41.6875,60.0,3.000,0.00000,1034.9375,-20.5375,NaN,0.0
3,2003-01-04,-10.2,-13.4,-6.8,0.0,0.2,13.8,270.0,6.6,270.0,...,-5.9,-13.0,47.7125,70.0,3.625,0.00000,1040.1000,-19.3250,NaN,0.0
4,2003-01-05,-12.8,-15.5,-9.1,0.0,0.0,12.0,250.0,6.1,270.0,...,-2.5,-13.1,36.6375,350.0,2.625,0.00000,1039.2375,-19.7625,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7178,2021-08-27,22.4,20.4,25.5,0.7,0.9,4.9,250.0,3.2,250.0,...,26.1,17.8,68.6500,350.0,2.250,0.00000,1013.3000,15.9250,NaN,0.0
7179,2021-08-28,23.6,19.7,28.2,0.0,0.0,7.3,270.0,3.9,270.0,...,28.4,18.9,75.6250,320.0,1.500,-2.07536,1013.3875,18.3375,NaN,0.0
7180,2021-08-29,23.7,21.9,26.3,0.7,0.9,5.6,340.0,3.4,320.0,...,21.9,18.8,92.9875,50.0,0.875,-2.07536,1014.1125,19.3625,NaN,0.0
7181,2021-08-30,24.2,21.2,27.7,0.0,0.0,4.5,270.0,2.9,250.0,...,24.3,21.4,93.1250,40.0,1.500,-2.07536,1013.2750,21.2125,NaN,0.0
7182,2021-08-31,20.5,18.1,23.1,12.4,77.4,9.3,70.0,4.9,70.0,...,21.7,18.8,94.7875,50.0,2.625,-2.07536,1012.6750,19.0500,NaN,0.0